# Generated by Django 5.2 on 2025-04-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendr_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('points', models.BigIntegerField(default=0)),
                ('streak', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='days_attended',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='days_missed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('members', models.ManyToManyField(related_name='groups', to='attendr_back.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='attendr_back.user'),
            preserve_default=False,
        ),
    ]
