# Generated by Django 5.2 on 2025-04-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendr_back', '0002_user_course_days_attended_course_days_missed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='frequency',
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.ManyToManyField(related_name='courses', to='attendr_back.day'),
        ),
    ]
