# Generated by Django 5.2 on 2025-04-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendr_back', '0003_day_remove_course_frequency_course_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
