# Generated by Django 5.2 on 2025-04-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendr_back', '0005_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='name',
        ),
    ]
