# Generated by Django 5.2 on 2025-04-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendr_back', '0006_remove_day_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('datetime', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendr_back.user')),
            ],
        ),
    ]
